// <auto-generated />
namespace Sports.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rolesecurities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rolesecurities));
        
        string IMigrationMetadata.Id
        {
            get { return "201711130235353_role-securities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
